query Category($id: ID!) {
    category(id: $id) {
        id
        products {
            id
            name
            price
            image
            stock
            new
        }
    }
}